[package]
name = "langram_benchmark"
version = "0.0.0"
authors = ["Dmitry Rodionov <gh@rdmtr.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
ahash = "0.8"
criterion = "0.5"
langram = { path = ".." }

[[bench]]
name = "benchmark"
harness = false
